DROP DATABASE IF EXISTS VietSecond;
CREATE DATABASE IF NOT EXISTS VietSecond;

USE VietSecond;

CREATE TABLE `User`(
userId INT PRIMARY KEY AUTO_INCREMENT,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(50) NOT NULL,
gender ENUM('MALE','FEMALE','UNKNOW'),
address VARCHAR(255) NOT NULL,
dateOfBirth DATE NOT NULL, 
phoneNumber VARCHAR(15) NOT NULL,
accountBalance LONGBLOB,
email  VARCHAR(100) NOT NULL,
userName VARCHAR(50) NOT NULL,
`password` VARCHAR(255) NOT NULL,
role ENUM('EMPLOYEE','ADMIN','SUPER_ADMIN')
)